CREATE SCHEMA MMNG;

CREATE TABLE MMNG.PAYMENTS
(
    PAYMENT_ID      VARCHAR(8),
    AMOUNT          FLOAT,
    ENTRY_DT        TIMESTAMP,

    FROM_NAME       VARCHAR(100),
    FROM_ACCOUNT_NB VARCHAR(50),

    TO_NAME         VARCHAR(100),
    TO_ACCOUNT_NB   VARCHAR(50),

    PRIMARY KEY (PAYMENT_ID)
);